# .github/workflows/chromatic.yml

# Workflow name
name: Chromatic

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    steps:
     - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn install --frozen-lockfile
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }
          exitZeroOnChanges: true